### ISSUE TITLE
`org-clock-helpers-insert-appt-clock` not working because default value of `org-clock-helpers-appt-clock-keywords` is `nil`

### ISSUE THREAD

**Issue by gsingh93** [mskorzhinskiy/org-clock-helpers#1]
I downloaded `org-clock-helpers.el` to a folder and put this in my emacs init file:

```
(use-package org-clock-helpers
  :load-path "~/.emacs.d/personal/"
  :config (org-clock-helpers-appt-clock-load))
```

Marking a TODO entry as DONE doesn't work by default. I checked the value of `org-clock-helpers-appt-clock-keywords`, and it seems to be `nil`. My guess is it's because it's set to `org-done-keywords` which is a buffer-local variable, so in my case it's `nil` when `org-clock-helpers-appt-clock-keywords` is defined, and `org-done-keywords` is non-nil after opening an org file.

Can you take a look at this?

**Comment by mskorzhinskiy** [comment]
Sure! Will fix that during the weekends. You can suggest a patch, I'll be happy to apply it too!

**Comment by mskorzhinskiy** [comment]
If your done keywords are something different from the default org-mode setting, please set the `org-clock-helpers-appt-clock-keywords` to your liking. If you need it to be buffer local too, there a way: https://stackoverflow.com/questions/21917049/how-can-i-set-buffer-local-value-for-a-variable-defined-by-defcustom
